# Generated by Django 5.2.5 on 2025-11-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_categories_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='last_name',
        ),
    ]
