# Generated by Django 5.2.5 on 2025-11-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_first_name_comment_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettersubscriber',
            old_name='name',
            new_name='full_name',
        ),
    ]
