# Generated by Django 5.2.5 on 2025-11-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, default='/media/samples/blog_default.jpg', null=True, upload_to='blog/'),
        ),
    ]
