# Generated by Django 5.2.5 on 2025-11-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, default='/media/samples/blog_default.jpg', upload_to='blog/'),
        ),
    ]
