# Generated by Django 5.2.5 on 2025-11-21 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='category',
        ),
    ]
