# Generated by Django 5.2.5 on 2025-12-21 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolioitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
